export const MES_ORG_STRUCTURE_VERSION = "mes_org_structure_2026_06_05_v1";

export const MES_SMT_WORK_CENTER_IDS = ["D3_L1", "D3_L2"];

export const MES_LEGACY_WORK_CENTER_ID_MAP = {
  smt: "D3_L1",
  aoi: "D3_AOI",
  wash: "D3_UW",
  manual: "D5",
  test: "D4",
  coating: "D3_CC",
  mechanic: "D9",
  assembly: "D9",
  warehouse: "D1",
  "smt-line:smt-line-1": "D3_L1",
  "smt-line:smt-line-2": "D3_L2",
  "smt-line:res-smt-1": "D3_L1",
  "smt-line:res-smt-2": "D3_L2",
};

export const MES_LEGACY_WORK_CENTER_NAME_MAP = {
  "SMT отдел": "D3",
  "STM отдел": "D3",
  "SMT-монтаж": "D3",
  "SMT-1": "D3_L1",
  "SMT-2": "D3_L2",
  "ОТК / AOI-контроль": "D3_AOI",
  "AOI-контроль": "D3_AOI",
  "Офлайн АОИ": "D3_AOI",
  "Отмывка": "D3_UW",
  "THT отдел": "D5",
  "Ручной монтаж": "D5",
  "ОТК / Испытания": "D4",
  "Тестирование": "D4",
  "Отдел ручной лакировки": "D3_MANUAL_CC",
  "Отдел селективной лакировки": "D3_CC",
  "Лакировка": "D3_CC",
  "Слесарный отдел": "D9",
  "Слесарный участок": "D9",
  "Сборочный отдел": "D9",
  "Сборка": "D9",
  "Отдел программной подготовки изделий": "D6",
  "Склад компонентов": "D1",
  "Склад готовой продукции": "D1",
  "Склад": "D1",
};

export const MES_OBSOLETE_WORK_CENTER_IDS = new Set([
  "smt",
  "aoi",
  "wash",
  "manual",
  "test",
  "coating",
  "mechanic",
  "assembly",
  "warehouse",
]);

export const MES_OBSOLETE_RESOURCE_IDS = new Set([
  "res-smt-1",
  "res-smt-2",
  "res-aoi-offline",
  "res-test",
  "res-manual-a",
  "eq-smt1-loader",
  "eq-smt1-inspect-conveyor",
  "eq-smt1-hanwha-s2",
  "eq-smt1-hanwha-l2",
  "eq-smt1-conveyor",
  "eq-smt1-oven",
  "eq-smt2-manual-feed",
  "eq-smt2-conveyor",
  "eq-smt2-hanwha-s2",
  "eq-smt2-oven",
  "eq-smt2-aoi",
  "eq-aoi-athena",
  "eq-warehouse",
]);

export const MES_WORK_CENTERS = [
  {
    id: "D1",
    name: "Склад",
    code: "WH",
    description: "Складской отдел: приход, выдача, перемещение, списание и инвентаризация.",
    unitType: "warehouse",
    owner: "",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 300,
    capacity: 2,
    workSchedule: "2/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D2",
    name: "Технологический отдел",
    code: "PE",
    description: "Отдел подготовки и сопровождения производства. Операции пока не определены.",
    unitType: "administrative",
    owner: "Кузнецов Дмитрий",
    isPlanningUnit: false,
    showInGantt: false,
    unitsPerHour: 0,
    capacity: 0,
    workSchedule: "",
    workMode: "",
    isActive: true,
  },
  {
    id: "D3",
    name: "Отдел поверхностного монтажа",
    code: "SMT",
    description: "Родительская технологическая группа. SMT-участки 1 и 2 планируются как отдельные производственные ресурсы.",
    unitType: "production",
    owner: "Федоров Максим",
    isPlanningUnit: false,
    showInGantt: false,
    unitsPerHour: 0,
    capacity: 0,
    workSchedule: "",
    workMode: "",
    isActive: true,
  },
  {
    id: "D3_L1",
    name: "Участок поверхностного монтажа 1",
    code: "SMT-1",
    description: "Отдельный производственный ресурс SMT-монтажа: внутренний маршрут оборудования работает последовательно.",
    unitType: "production",
    parentWorkCenterId: "D3",
    owner: "Федоров Максим",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 55,
    capacity: 1,
    workSchedule: "2/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D3_L2",
    name: "Участок поверхностного монтажа 2",
    code: "SMT-2",
    description: "Отдельный производственный ресурс SMT-монтажа с внутренним маршрутом оборудования.",
    unitType: "production",
    parentWorkCenterId: "D3",
    owner: "Федоров Максим",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 50,
    capacity: 1,
    workSchedule: "2/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D3_AOI",
    name: "Отдел автоматической оптической инспекции",
    code: "AOI",
    description: "Отдел контроля с АОИ QUICK A300T.",
    unitType: "quality",
    parentWorkCenterId: "D3",
    owner: "Федоров Максим",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 110,
    capacity: 1,
    workSchedule: "2/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D3_UW",
    name: "Отдел ультразвуковой отмывки",
    code: "UW",
    description: "Отмывка плат. Правила выбора оборудования по вариантам отмывки требуют уточнения.",
    unitType: "production",
    parentWorkCenterId: "D3",
    owner: "Федоров Максим",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 150,
    capacity: 2,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D3_MANUAL_CC",
    name: "Отдел ручной лакировки",
    code: "COAT-M",
    description: "Ручная лакировка. Оборудование или рабочее место пока не определено.",
    unitType: "production",
    parentWorkCenterId: "D3",
    owner: "Федоров Максим",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 80,
    capacity: 1,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D3_CC",
    name: "Отдел селективной влагозащиты",
    code: "CC",
    description: "Селективная влагозащита с выделенным оборудованием / рабочим местом.",
    unitType: "production",
    parentWorkCenterId: "D3",
    owner: "Мельникова Оксана",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 80,
    capacity: 1,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D4",
    name: "Отдел технического контроля",
    code: "QC",
    description: "ОТК: промежуточный и финальный технический контроль.",
    unitType: "quality",
    owner: "Зайцева Наталья",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 35,
    capacity: 5,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D5",
    name: "Отдел ручного монтажа",
    code: "THT",
    description: "Ручной выводной монтаж, 4 линии, 27 исполнителей.",
    unitType: "production",
    owner: "",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 25,
    capacity: 27,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D6",
    name: "Отдел программной подготовки изделий",
    code: "PRG",
    description: "Прошивка и нагрузочное тестирование.",
    unitType: "production",
    owner: "Алексеев Евгений",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 35,
    capacity: 5,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D9",
    name: "Слесарно-сборочный отдел",
    code: "BBA",
    description: "Слесарно-сборочные операции и финальная механическая сборка.",
    unitType: "production",
    owner: "Рябов Валентин",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 45,
    capacity: 5,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
  {
    id: "D11",
    name: "Отдел маркировки и упаковки",
    code: "LAB",
    description: "Финишные операции: маркировка и упаковка.",
    unitType: "production",
    owner: "Терентьева Ольга",
    isPlanningUnit: true,
    showInGantt: true,
    unitsPerHour: 120,
    capacity: 3,
    workSchedule: "5/2",
    workMode: "08:00-20:00",
    isActive: true,
  },
];

export const MES_PRODUCTION_RESOURCES = [
  { id: "D1_STAFF", name: "Кладовщики склада", type: "staff", workCenterId: "D1", capacity: "3 исполнителя", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D3_SMT_STAFF", name: "Операторы участков поверхностного монтажа 1 и 2", type: "staff", workCenterId: "D3", capacity: "4 оператора", participatesInPlanning: "no", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D3_L1", name: "SMT участок 1", type: "aggregate", workCenterId: "D3_L1", capacity: "1 операция", baseCph: 32000, efficiency: 88, changeoverMin: 18, participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D3_L1_E1", name: "Принтер паяльной пасты GDK Prostar", type: "machine", workCenterId: "D3_L1", parentResourceId: "D3_L1", inventory: "SMT1-01", participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_L1_E2", name: "Установщик компонентов DECAN S2", type: "machine", workCenterId: "D3_L1", parentResourceId: "D3_L1", inventory: "SMT1-02", baseCph: 92000, participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_L1_E3", name: "Установщик компонентов DECAN L2", type: "machine", workCenterId: "D3_L1", parentResourceId: "D3_L1", inventory: "SMT1-03", baseCph: 56000, participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_L1_E4", name: "Печь оплавления JTR-800", type: "machine", workCenterId: "D3_L1", parentResourceId: "D3_L1", inventory: "SMT1-04", participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_L2", name: "SMT участок 2", type: "aggregate", workCenterId: "D3_L2", capacity: "1 операция", baseCph: 28000, efficiency: 82, changeoverMin: 24, participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D3_L2_E1", name: "Принтер паяльной пасты GDK Prostar", type: "machine", workCenterId: "D3_L2", parentResourceId: "D3_L2", inventory: "SMT2-01", participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_L2_E2", name: "Установщик компонентов DECAN S2", type: "machine", workCenterId: "D3_L2", parentResourceId: "D3_L2", inventory: "SMT2-02", baseCph: 92000, participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_L2_E4", name: "Печь оплавления JTR-800", type: "machine", workCenterId: "D3_L2", parentResourceId: "D3_L2", inventory: "SMT2-03", participatesInPlanning: "no", participatesInCalculation: "no", status: "Работает" },
  { id: "D3_AOI_E1", name: "АОИ-установка QUICK A300T", type: "machine", workCenterId: "D3_AOI", capacity: "1 установка", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Работает" },
  { id: "D3_UW_E1", name: "Ручная малая ванна УЗ", type: "equipment", workCenterId: "D3_UW", capacity: "1 ванна", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Работает" },
  { id: "D3_UW_E2", name: "Большая ванна УЗ", type: "equipment", workCenterId: "D3_UW", capacity: "1 ванна", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Работает" },
  { id: "D3_UW_E3", name: "Комплекс УЗ", type: "equipment", workCenterId: "D3_UW", capacity: "1 комплекс", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Работает" },
  { id: "D3_MANUAL_CC_STAFF", name: "Лакировщик ручной лакировки", type: "staff", workCenterId: "D3_MANUAL_CC", capacity: "1 исполнитель", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D3_CC_E1", name: "Селективная влагозащита", type: "machine", workCenterId: "D3_CC", capacity: "1 ресурс", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Работает" },
  { id: "D3_CC_STAFF", name: "Операторы селективной влагозащиты", type: "staff", workCenterId: "D3_CC", capacity: "6 исполнителей", participatesInPlanning: "no", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D4_STAFF", name: "Специалисты технического контроля", type: "staff", workCenterId: "D4", capacity: "6 исполнителей", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D5_STAFF", name: "Монтажники ручного монтажа", type: "staff", workCenterId: "D5", capacity: "27 исполнителей", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D6_STAFF", name: "Специалисты программной подготовки изделий", type: "staff", workCenterId: "D6", capacity: "6 исполнителей", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D9_STAFF", name: "Слесари-сборщики", type: "staff", workCenterId: "D9", capacity: "6 исполнителей", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
  { id: "D11_STAFF", name: "Операторы маркировки и упаковки", type: "staff", workCenterId: "D11", capacity: "4 исполнителя", participatesInPlanning: "yes", participatesInCalculation: "yes", status: "Доступен" },
];

export const MES_OPERATION_MAP = [
  { id: "D1_OP1", name: "Приход от поставщика", code: "WH-010", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP2", name: "Поступление из производства", code: "WH-020", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, isOutputReceipt: true, warehouseFlow: "production_receipt", status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP3", name: "Выдача в производство", code: "WH-030", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP4", name: "Возврат из производства", code: "WH-040", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP5", name: "Перемещение", code: "WH-050", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP6", name: "Списание", code: "WH-060", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP7", name: "Инвентаризация", code: "WH-070", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D1_R1", "D1_R2"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D2_OPS_PLACEHOLDER", name: "Операции технологического отдела", code: "PE-000", workCenterId: "D2", unitsPerHour: 0, requiresBatch: false, isWarehouse: false, status: "Активен", coverage: "blocked", executorStatus: "defined", executorRoleIds: ["D2_R1", "D2_R2", "D2_R3", "D2_R4", "D2_R5"], equipmentStatus: "not_applicable_until_operations_defined", equipmentIds: [], gaps: ["Состав операций технологического отдела не определен."] },
  { id: "D3_L1_OP", name: "SMT-монтаж", code: "SMT-010", workCenterId: "D3", routeWorkCenterId: "D3", planningWorkCenterIds: ["D3_L1", "D3_L2"], unitsPerHour: 55, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "complete", executorStatus: "defined_shared", executorRoleIds: ["D3_R2"], sharedResourceId: "D3_SMT_STAFF", equipmentStatus: "defined_by_planning", equipmentIds: ["D3_L1_E1", "D3_L1_E2", "D3_L1_E3", "D3_L1_E4", "D3_L2_E1", "D3_L2_E2", "D3_L2_E4"], resourceSemantics: "route_instruction_with_planning_resource_selection", businessOutput: "Смонтированная печатная плата после SMT-монтажа", routeSemantics: "Маршрутная карта фиксирует технологическую операцию SMT; конкретный SMT-участок выбирается при планировании." },
  { id: "D3_L2_OP", name: "SMT-монтаж", code: "SMT2-010", workCenterId: "D3_L2", unitsPerHour: 50, requiresBatch: true, isWarehouse: false, status: "Отключен", coverage: "legacy_alias", legacyAliasOf: "D3_L1_OP", executorStatus: "defined_shared", executorRoleIds: ["D3_R2"], sharedResourceId: "D3_SMT_STAFF", equipmentStatus: "defined_route", equipmentIds: ["D3_L2_E1", "D3_L2_E2", "D3_L2_E4"], resourceSemantics: "legacy_line_specific_operation", businessOutput: "Смонтированная печатная плата после SMT-монтажа", routeSemantics: "Историческая строка для старых маршрутов; в новых маршрутных картах используется общий SMT-монтаж." },
  { id: "D3_AOI_OP", name: "Оптическая инспекция", code: "AOI-010", workCenterId: "D3_AOI", unitsPerHour: 110, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D3_R3"], equipmentStatus: "defined", equipmentIds: ["D3_AOI_E1"] },
  { id: "D3_UW_OP", name: "Отмывка", code: "UW-010", workCenterId: "D3_UW", unitsPerHour: 150, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D3_UW_R1"], executorPersonIds: ["D3_UW_P1", "D3_UW_P2"], equipmentStatus: "defined_pool", equipmentIds: ["D3_UW_E1", "D3_UW_E2", "D3_UW_E3"], gaps: ["Не задано, какое оборудование применяется к каким вариантам отмывки."] },
  { id: "D3_MANUAL_CC_OP", name: "Ручная лакировка", code: "COATM-010", workCenterId: "D3_MANUAL_CC", unitsPerHour: 80, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D3_MANUAL_CC_R1"], executorPersonIds: ["D3_MANUAL_CC_P1"], equipmentStatus: "missing", equipmentIds: [], gaps: ["Оборудование или рабочее место ручной лакировки не определено."] },
  { id: "D3_CC_OP", name: "Селективная влагозащита", code: "CC-010", workCenterId: "D3_CC", unitsPerHour: 80, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["D3_CC_R1", "D3_CC_R2"], equipmentStatus: "defined", equipmentIds: ["D3_CC_E1"] },
  { id: "D4_OP1", name: "Технический контроль промежуточный", code: "QC-010", workCenterId: "D4", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D4_R1", "D4_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Средства контроля и измерительное оборудование не заведены как ресурсы."] },
  { id: "D4_OP2", name: "Технический контроль готовой продукции", code: "QC-020", workCenterId: "D4", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D4_R1", "D4_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Средства контроля и измерительное оборудование не заведены как ресурсы."] },
  { id: "D5_OP1", name: "Выводной монтаж (пайка)", code: "THT-010", workCenterId: "D5", unitsPerHour: 25, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined_by_lines", executorRoleIds: ["D5_L1_R1", "D5_L1_R2", "D5_L2_R1", "D5_L2_R2", "D5_L3_R1", "D5_L3_R2", "D5_L4_R1", "D5_L4_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Паяльные места, инструмент и оснастка не заведены как оборудование."] },
  { id: "D6_OP1", name: "Прошивка", code: "PRG-010", workCenterId: "D6", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D6_R1", "D6_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Программаторы, стенды или рабочие места прошивки не заведены как оборудование."] },
  { id: "D6_OP2", name: "Нагрузочное тестирование", code: "PRG-020", workCenterId: "D6", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D6_R1", "D6_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Стенды нагрузочного тестирования не заведены как оборудование."] },
  { id: "D9_OP1", name: "Слесарная операция", code: "BBA-010", workCenterId: "D9", unitsPerHour: 45, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D9_R1", "D9_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Слесарный инструмент, рабочие места или оснастка не заведены как оборудование."] },
  { id: "D11_OP1", name: "Маркировка", code: "LAB-010", workCenterId: "D11", unitsPerHour: 120, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D11_R1", "D11_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Оборудование маркировки не заведено как ресурс."] },
  { id: "D11_OP2", name: "Упаковка", code: "LAB-020", workCenterId: "D11", unitsPerHour: 120, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["D11_R1", "D11_R2"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Упаковочные места, инструмент или оборудование не заведены как ресурс."] },
];
