export const MES_ORG_STRUCTURE_VERSION = "mes_org_structure_2026_06_05_v1";

export const MES_SMT_WORK_CENTER_IDS = ["D3_L1", "D3_L2"];

export const MES_LEGACY_WORK_CENTER_ID_MAP = {
  smt: "D3_L1",
  aoi: "D3_AOI",
  wash: "D3_UW",
  manual: "D5",
  test: "D4",
  coating: "D3_CC",
  mechanic: "D9",
  assembly: "D9",
  warehouse: "D1",
  "smt-line:smt-line-1": "D3_L1",
  "smt-line:smt-line-2": "D3_L2",
  "smt-line:res-smt-1": "D3_L1",
  "smt-line:res-smt-2": "D3_L2",
  D3_MANUAL_CC: "D3_CC",
};

export const MES_LEGACY_WORK_CENTER_NAME_MAP = {
  "SMT отдел": "D3",
  "STM отдел": "D3",
  "SMT-монтаж": "D3",
  "SMT-1": "D3_L1",
  "SMT-2": "D3_L2",
  "ОТК / AOI-контроль": "D3_AOI",
  "AOI-контроль": "D3_AOI",
  "Офлайн АОИ": "D3_AOI",
  "Отмывка": "D3_UW",
  "THT отдел": "D5",
  "Ручной монтаж": "D5",
  "ОТК / Испытания": "D4",
  "Тестирование": "D4",
  "Отдел ручной лакировки": "D3_CC",
  "Отдел селективной лакировки": "D3_CC",
  "Лакировка": "D3_CC",
  "Слесарный отдел": "D9",
  "Слесарный участок": "D9",
  "Сборочный отдел": "D9",
  "Сборка": "D9",
  "Отдел программной подготовки изделий": "D6",
  "Склад компонентов": "D1",
  "Склад готовой продукции": "D1",
  "Склад": "D1",
};

export const MES_OBSOLETE_WORK_CENTER_IDS = new Set([
  "smt",
  "aoi",
  "wash",
  "manual",
  "test",
  "coating",
  "mechanic",
  "assembly",
  "warehouse",
]);

export const MES_OBSOLETE_RESOURCE_IDS = new Set([
  "res-smt-1",
  "res-smt-2",
  "res-aoi-offline",
  "res-test",
  "res-manual-a",
  "eq-smt1-loader",
  "eq-smt1-inspect-conveyor",
  "eq-smt1-hanwha-s2",
  "eq-smt1-hanwha-l2",
  "eq-smt1-conveyor",
  "eq-smt1-oven",
  "eq-smt2-manual-feed",
  "eq-smt2-conveyor",
  "eq-smt2-hanwha-s2",
  "eq-smt2-oven",
  "eq-smt2-aoi",
  "eq-aoi-athena",
  "eq-warehouse",
]);

export const MES_OPERATION_MAP = [
  { id: "D1_OP1", name: "Приход от поставщика", code: "WH-010", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP2", name: "Поступление из производства", code: "WH-020", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, isOutputReceipt: true, warehouseFlow: "production_receipt", status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP3", name: "Выдача в производство", code: "WH-030", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP4", name: "Возврат из производства", code: "WH-040", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP5", name: "Перемещение", code: "WH-050", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP6", name: "Списание", code: "WH-060", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D1_OP7", name: "Инвентаризация", code: "WH-070", workCenterId: "D1", unitsPerHour: 300, requiresBatch: false, isWarehouse: true, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-WAREHOUSE-STARSHIY-KLADOVSCHIK-1", "ROLE-D-WAREHOUSE-KLADOVSCHIK-1"], equipmentStatus: "not_required_for_business_operation", equipmentIds: [] },
  { id: "D2_OPS_PLACEHOLDER", name: "Операции технологического отдела", code: "PE-000", workCenterId: "D2", unitsPerHour: 0, requiresBatch: false, isWarehouse: false, status: "Активен", coverage: "blocked", executorStatus: "defined", executorRoleIds: ["ROLE-D-TECH-RUKOVODITEL-TEHNOLOGICHESKOGO-NAPR-1", "ROLE-D-TECH-TEHNOLOG-PROIZVODSTVA-1", "ROLE-D-TECH-MLADSHIY-DISPETCHER-PROIZVODSTVA-1", "ROLE-D-TECH-SPECIALIST-PO-NORMIROVANIYU-TRUDA-1", "ROLE-D-TECH-SPECIALIST-PO-SNABZHENIYU-PROIZVOD-1"], equipmentStatus: "not_applicable_until_operations_defined", equipmentIds: [], gaps: ["Состав операций технологического отдела не определен."] },
  { id: "D3_L1_OP", name: "SMT-монтаж", code: "SMT-010", workCenterId: "D3", routeWorkCenterId: "D3", planningWorkCenterIds: ["D3_L1", "D3_L2"], unitsPerHour: 55, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "complete", executorStatus: "defined_shared", executorRoleIds: ["ROLE-S-SMT-1-OPERATOR-LINII-POVERHNOSTNOGO-MONT-1", "ROLE-S-SMT-2-OPERATOR-LINII-POVERHNOSTNOGO-MONT-1", "ROLE-S-SMT-1-MLADSHIY-OPERATOR-LINII-POVERHNOST-1", "ROLE-S-SMT-2-MLADSHIY-OPERATOR-LINII-POVERHNOST-1"], sharedResourceId: "D3_MATRIX", equipmentStatus: "defined_by_planning", equipmentIds: ["EQ-S-SMT-1-S2-L2-1", "EQ-S-SMT-2-S2-1"], resourceSemantics: "route_instruction_with_planning_resource_selection", businessOutput: "Смонтированная печатная плата после SMT-монтажа", routeSemantics: "Маршрутная карта фиксирует технологическую операцию SMT; конкретный SMT-участок выбирается при планировании." },
  { id: "D3_L2_OP", name: "SMT-монтаж", code: "SMT2-010", workCenterId: "D3_L2", unitsPerHour: 50, requiresBatch: true, isWarehouse: false, status: "Отключен", coverage: "legacy_alias", legacyAliasOf: "D3_L1_OP", executorStatus: "defined_shared", executorRoleIds: ["ROLE-S-SMT-1-OPERATOR-LINII-POVERHNOSTNOGO-MONT-1", "ROLE-S-SMT-2-OPERATOR-LINII-POVERHNOSTNOGO-MONT-1", "ROLE-S-SMT-1-MLADSHIY-OPERATOR-LINII-POVERHNOST-1", "ROLE-S-SMT-2-MLADSHIY-OPERATOR-LINII-POVERHNOST-1"], sharedResourceId: "D3_L2_MATRIX", equipmentStatus: "defined_route", equipmentIds: ["EQ-S-SMT-2-S2-1"], resourceSemantics: "legacy_line_specific_operation", businessOutput: "Смонтированная печатная плата после SMT-монтажа", routeSemantics: "Историческая строка для старых маршрутов; в новых маршрутных картах используется общий SMT-монтаж." },
  { id: "D3_AOI_OP", name: "Оптическая инспекция", code: "AOI-010", workCenterId: "D3_AOI", unitsPerHour: 110, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-S-AOI-OPERATOR-LINII-POVERHNOSTNOGO-MONT-1"], equipmentStatus: "defined", equipmentIds: ["EQ-S-AOI-PEMTRON-1"] },
  { id: "D3_UW_OP", name: "Отмывка", code: "UW-010", workCenterId: "D3_UW", unitsPerHour: 150, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-S-WASH-SPECIALIST-PO-OTMYVKE-PECHATNYH-PL-1"], executorPersonIds: ["ROLE-S-WASH-SPECIALIST-PO-OTMYVKE-PECHATNYH-PL-1-EMP-01"], equipmentStatus: "defined_pool", equipmentIds: ["EQ-S-WASH-UZ-3-1-1", "EQ-S-WASH-STRUYNAYA-OTMYVKA-1"], gaps: ["Не задано, какое оборудование применяется к каким вариантам отмывки."] },
  { id: "D3_MANUAL_CC_OP", name: "Ручная лакировка", code: "COATM-010", workCenterId: "D3_CC", unitsPerHour: 80, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-D-COATING-SPECIALIST-PO-NANESENIYU-VLAGOZASC-1"], executorPersonIds: ["ROLE-D-COATING-SPECIALIST-PO-NANESENIYU-VLAGOZASC-1-EMP-01"], equipmentStatus: "missing", equipmentIds: [], gaps: ["Ручная лакировка живет как операция внутри матричного отдела влагозащиты; отдельный рабочий центр не создается."] },
  { id: "D3_CC_OP", name: "Селективная влагозащита", code: "CC-010", workCenterId: "D3_CC", unitsPerHour: 80, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "complete", executorStatus: "defined", executorRoleIds: ["ROLE-D-COATING-MLADSHIY-OPERATOR-LINII-SELEKTIVNO-1", "ROLE-D-COATING-SPECIALIST-PO-NANESENIYU-VLAGOZASC-1"], equipmentStatus: "defined", equipmentIds: ["EQ-D-COATING-NONAME-1"] },
  { id: "D4_OP1", name: "Технический контроль промежуточный", code: "QC-010", workCenterId: "D4", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-D-QC-SPECIALIST-PO-TEHNICHESKOMU-KONTRO-1", "ROLE-D-QC-STARSHIY-SPECIALIST-TEHNICHESKOGO--1", "ROLE-D-QC-SPECIALIST-TEHNICHESKOGO-KONTROLYA-1", "ROLE-D-QC-MLADSHIY-SPECIALIST-TEHNICHESKOGO--1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Средства контроля и измерительное оборудование не заведены как ресурсы."] },
  { id: "D4_OP2", name: "Технический контроль готовой продукции", code: "QC-020", workCenterId: "D4", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-D-QC-SPECIALIST-PO-TEHNICHESKOMU-KONTRO-1", "ROLE-D-QC-STARSHIY-SPECIALIST-TEHNICHESKOGO--1", "ROLE-D-QC-SPECIALIST-TEHNICHESKOGO-KONTROLYA-1", "ROLE-D-QC-MLADSHIY-SPECIALIST-TEHNICHESKOGO--1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Средства контроля и измерительное оборудование не заведены как ресурсы."] },
  { id: "D5_OP1", name: "Выводной монтаж (пайка)", code: "THT-010", workCenterId: "D5", unitsPerHour: 25, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined_by_lines", executorRoleIds: ["ROLE-S-MANUAL-1-STARSHIY-MONTAZHNIK-LINII-1", "ROLE-S-MANUAL-1-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-1-MLADSHIY-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-2-STARSHIY-MONTAZHNIK-LINII-1", "ROLE-S-MANUAL-2-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-2-MLADSHIY-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-3-STARSHIY-MONTAZHNIK-LINII-1", "ROLE-S-MANUAL-3-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-3-MLADSHIY-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-4-STARSHIY-MONTAZHNIK-LINII-1", "ROLE-S-MANUAL-4-MONTAZHNIK-REAIP-1", "ROLE-S-MANUAL-4-MLADSHIY-MONTAZHNIK-REAIP-1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Паяльные места, инструмент и оснастка не заведены как оборудование."] },
  { id: "D6_OP1", name: "Прошивка", code: "PRG-010", workCenterId: "D6", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-D-PROGRAMMING-STARSHIY-SPECIALIST-PROGRAMMNOY-PO-1", "ROLE-D-PROGRAMMING-SPECIALIST-PROGRAMMNOY-PODGOTOVKI--1", "ROLE-D-PROGRAMMING-MLADSHIY-SPECIALIST-PROGRAMMNOY-PO-1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Программаторы, стенды или рабочие места прошивки не заведены как оборудование."] },
  { id: "D6_OP2", name: "Нагрузочное тестирование", code: "PRG-020", workCenterId: "D6", unitsPerHour: 35, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-D-PROGRAMMING-STARSHIY-SPECIALIST-PROGRAMMNOY-PO-1", "ROLE-D-PROGRAMMING-SPECIALIST-PROGRAMMNOY-PODGOTOVKI--1", "ROLE-D-PROGRAMMING-MLADSHIY-SPECIALIST-PROGRAMMNOY-PO-1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Стенды нагрузочного тестирования не заведены как оборудование."] },
  { id: "D9_OP1", name: "Слесарная операция", code: "BBA-010", workCenterId: "D9", unitsPerHour: 45, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-S-LOCKSMITH-1-SLESAR-SBORSCHIK-1", "ROLE-S-LOCKSMITH-1-MLADSHIY-SLESAR-SBORSCHIK-1", "ROLE-S-LOCKSMITH-1-MLADSHIY-SPECIALIST-PROIZVODSTVA-1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Слесарный инструмент, рабочие места или оснастка не заведены как оборудование."] },
  { id: "D11_OP1", name: "Маркировка", code: "LAB-010", workCenterId: "D11", unitsPerHour: 120, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-S-PACKING-UPAKOVSCHIK-1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Оборудование маркировки не заведено как ресурс."] },
  { id: "D11_OP2", name: "Упаковка", code: "LAB-020", workCenterId: "D11", unitsPerHour: 120, requiresBatch: true, isWarehouse: false, status: "Активен", coverage: "partial", executorStatus: "defined", executorRoleIds: ["ROLE-S-PACKING-UPAKOVSCHIK-1"], equipmentStatus: "not_modeled", equipmentIds: [], gaps: ["Упаковочные места, инструмент или оборудование не заведены как ресурс."] },
];
