import {
  HARD_UI_RUNTIME_MODULE_IDS,
  LEGACY_UI_RUNTIME_MODULE_IDS,
  PARTIAL_UI_RUNTIME_MODULE_IDS,
  SPECIAL_UI_RUNTIME_CONTRACTS,
  SPECIAL_UI_RUNTIME_MODULE_IDS,
  UI_RUNTIME_COVERAGE_NOTES,
} from "./ui/contracts/runtime-contracts.js";
import { UI_HARDENING_PLAN_STAGES } from "./ui/contracts/hardening-plan-contracts.js";

export {
  HARD_UI_RUNTIME_MODULE_IDS,
  LEGACY_UI_RUNTIME_MODULE_IDS,
  PARTIAL_UI_RUNTIME_MODULE_IDS,
  SPECIAL_UI_RUNTIME_CONTRACTS,
  SPECIAL_UI_RUNTIME_MODULE_IDS,
  UI_RUNTIME_COVERAGE_NOTES,
  UI_HARDENING_PLAN_STAGES,
};

export const UI_RUNTIME_COMPONENT_CONTRACTS = [
  {
    component: "AppShell",
    helperNames: ["renderUiAppShell"],
    cssSelectors: ["main.app-shell[data-layout=\"app-shell\"]"],
    purpose: "Главная оболочка приложения, меню, topbar и слой модалок.",
  },
  {
    component: "ModulePage",
    helperNames: ["renderUiModulePage"],
    cssSelectors: [".ui-module-page"],
    purpose: "Единая страница модуля: sidebar + workspace или полноширинная рабочая область.",
  },
  {
    component: "ModuleSidebar",
    helperNames: ["renderUiModuleSidebar"],
    cssSelectors: [".ui-module-sidebar", ".module-data-sidebar"],
    purpose: "Внутренний сайдбар модуля с одинаковой шириной, отступами и списками.",
  },
  {
    component: "ModuleWorkspace",
    helperNames: ["renderUiModulePage"],
    cssSelectors: [".ui-module-workspace", ".module-data-workspace"],
    purpose: "Рабочая область модуля; не должна создавать случайные вложенные scroll-слои.",
  },
  {
    component: "ModuleContent",
    helperNames: ["renderUiModulePage"],
    cssSelectors: [".ui-module-content", ".module-data-content"],
    purpose: "Вертикальный поток блоков внутри рабочей области.",
  },
  {
    component: "ModuleHeader",
    helperNames: ["renderUiModuleHeader"],
    cssSelectors: [".ui-module-header", ".directory-header"],
    purpose: "Заголовок рабочей области с аннотацией и actions.",
  },
  {
    component: "Panel",
    helperNames: ["renderUiPanel"],
    cssSelectors: [".ui-panel", ".module-panel"],
    purpose: "Основной блок интерфейса с управляемыми отступами и заголовком.",
  },
  {
    component: "PanelHead",
    helperNames: ["renderUiPanelHead"],
    cssSelectors: [".ui-panel-head"],
    purpose: "Заголовок панели; отвечает за inset, переносы и правый action-slot.",
  },
  {
    component: "PanelBody",
    helperNames: ["renderUiPanelBody"],
    cssSelectors: [".ui-panel-body"],
    purpose: "Тело панели; основной контролируемый источник внутренних отступов.",
  },
  {
    component: "PanelFooter",
    helperNames: ["renderUiPanelFooter"],
    cssSelectors: [".ui-panel-footer"],
    purpose: "Нижняя action-зона панели или модалки.",
  },
  {
    component: "ActionButton",
    helperNames: ["renderUiActionButton"],
    cssSelectors: [".ui-action-button", ".primary-button", ".secondary-button", ".icon-button", ".table-icon-button"],
    purpose: "Все кликабельные кнопки, включая иконки и table actions.",
  },
  {
    component: "ActionBar",
    helperNames: ["renderUiActionBar"],
    cssSelectors: [".ui-action-bar"],
    purpose: "Группа действий с единым gap и переносом.",
  },
  {
    component: "Toolbar",
    helperNames: ["renderUiToolbar"],
    cssSelectors: [".ui-toolbar"],
    purpose: "Горизонтальная панель управления модулем или периодом с единым gap, переносом и плотностью.",
  },
  {
    component: "FilterBar",
    helperNames: ["renderUiFilterBar"],
    cssSelectors: [".ui-filter-bar"],
    purpose: "Строка фильтров/сегментов с единым переносом и управляемой плотностью.",
  },
  {
    component: "SidebarItem",
    helperNames: ["renderUiSidebarItem"],
    cssSelectors: [".ui-sidebar-item"],
    purpose: "Строка или карточка списка внутри сайдбара.",
  },
  {
    component: "TableWrap",
    helperNames: ["renderUiTableWrap"],
    cssSelectors: [".ui-table-wrap", ".ui-table", ".ui-table-row", ".ui-table-cell", ".ui-tree-cell", ".ui-tree-toggle", "[data-layout=\"table\"]"],
    purpose: "Обертка таблицы с локальным горизонтальным scroll и запретом внутреннего vertical scroll.",
  },
  {
    component: "FormField",
    helperNames: ["renderUiFormField"],
    cssSelectors: [".ui-form-field", ".form-field"],
    purpose: "Единая высота, подпись и inset для input/select/textarea.",
  },
  {
    component: "Dropdown",
    helperNames: ["renderUiDropdownFrame"],
    cssSelectors: [".ui-dropdown", ".dense-inline-select", ".directory-column-filter"],
    purpose: "Выпадающий список с viewport-safe меню.",
  },
  {
    component: "Modal",
    helperNames: ["renderUiModalFrame", "renderUiModalShell"],
    cssSelectors: [".ui-modal", ".modal"],
    purpose: "Модальное окно с управляемой шириной, высотой и внутренним scroll.",
  },
  {
    component: "Drawer",
    helperNames: ["renderUiDrawerFrame", "renderUiDrawerShell"],
    cssSelectors: [".ui-drawer", ".detail-drawer", ".slot-drawer"],
    purpose: "Выдвижная карточка/панель деталей.",
  },
  {
    component: "GanttBar",
    helperNames: ["renderUiGanttBar"],
    cssSelectors: [".ui-gantt-bar", ".operation-slot"],
    purpose: "Демо/контрактная колбаска план/распределено/факт.",
  },
  {
    component: "StatusToken",
    helperNames: ["renderUiStatusToken"],
    cssSelectors: [".ui-status-token", ".mes-signal"],
    purpose: "Статус, риск, предупреждение, demo/calculation token.",
  },
  {
    component: "DemoBadge",
    helperNames: ["renderUiDemoBadge"],
    cssSelectors: [".ui-demo-badge"],
    purpose: "Плашка демо-функции, которая не влияет на систему.",
  },
  {
    component: "DemoMarker",
    helperNames: ["renderUiDemoCornerMarker", "renderUiDemoInteractiveMarker", "renderUiDemoInlineMarker"],
    cssSelectors: [".ui-demo-corner-marker", ".ui-demo-inline-marker"],
    purpose: "Малый D-маркер для UI-заглушек и демо-элементов.",
  },
  {
    component: "EmptyState",
    helperNames: ["renderUiEmptyState"],
    cssSelectors: [".ui-empty-state", ".module-preview-empty"],
    purpose: "Пустое состояние без самодельных карточек.",
  },
];

export const UI_RUNTIME_STYLE_TOKENS = [
  "--mes-ui-bg",
  "--mes-ui-bg-grid",
  "--mes-ui-bg-gradient",
  "--mes-ui-module-page-background",
  "--mes-ui-module-page-background-size",
  "--mes-ui-module-page-background-repeat",
  "--mes-ui-surface",
  "--mes-ui-surface-soft",
  "--mes-ui-surface-raised",
  "--mes-ui-surface-muted",
  "--mes-ui-surface-selected",
  "--mes-ui-surface-page",
  "--mes-ui-surface-panel",
  "--mes-ui-surface-panel-soft",
  "--mes-ui-surface-panel-raised",
  "--mes-ui-surface-control",
  "--mes-ui-surface-hover",
  "--mes-ui-surface-inverse",
  "--mes-ui-line",
  "--mes-ui-line-strong",
  "--mes-ui-line-soft",
  "--mes-ui-border-width",
  "--mes-ui-border-soft",
  "--mes-ui-border-default",
  "--mes-ui-border-strong",
  "--mes-ui-text",
  "--mes-ui-muted",
  "--mes-ui-text-muted",
  "--mes-ui-text-soft",
  "--mes-ui-text-inverse",
  "--mes-ui-primary",
  "--mes-ui-sidebar-bg",
  "--mes-ui-accent",
  "--mes-ui-accent-soft",
  "--mes-ui-focus-ring",
  "--mes-ui-focus-ring-strong",
  "--mes-ui-success",
  "--mes-ui-success-soft",
  "--mes-ui-success-border",
  "--mes-ui-warning",
  "--mes-ui-warning-soft",
  "--mes-ui-warning-border",
  "--mes-ui-danger",
  "--mes-ui-danger-soft",
  "--mes-ui-danger-border",
  "--mes-ui-neutral",
  "--mes-ui-neutral-soft",
  "--mes-ui-neutral-border",
  "--mes-ui-module-sidebar-width",
  "--mes-ui-work-sidebar-width",
  "--mes-space-0",
  "--mes-space-1",
  "--mes-space-2",
  "--mes-space-3",
  "--mes-space-4",
  "--mes-space-5",
  "--mes-space-6",
  "--mes-space-8",
  "--mes-space-10",
  "--mes-space-12",
  "--mes-density-page-gap",
  "--mes-density-panel-gap",
  "--mes-density-card-gap",
  "--mes-density-table-row-compact",
  "--mes-density-table-row-default",
  "--mes-density-table-row-comfortable",
  "--mes-ui-density-page",
  "--mes-ui-density-gap",
  "--mes-ui-panel-gap",
  "--mes-ui-panel-head-padding",
  "--mes-ui-panel-body-padding",
  "--mes-ui-panel-footer-padding",
  "--mes-ui-control-height",
  "--mes-ui-control-height-compact",
  "--mes-ui-control-height-default",
  "--mes-ui-control-height-touch",
  "--mes-ui-control-padding-x",
  "--mes-ui-control-gap",
  "--mes-control-height-compact",
  "--mes-control-height-default",
  "--mes-control-height-touch",
  "--mes-control-padding-x",
  "--mes-control-gap",
  "--mes-ui-icon-button-size",
  "--mes-ui-table-icon-button-size",
  "--mes-ui-topbar-compact-action-size",
  "--mes-icon-button-size",
  "--mes-table-icon-button-size",
  "--mes-ui-icon-size-sm",
  "--mes-ui-icon-size-md",
  "--mes-ui-icon-size-lg",
  "--mes-ui-form-control-height",
  "--mes-ui-table-row-height",
  "--mes-ui-table-row-height-compact",
  "--mes-ui-table-row-height-default",
  "--mes-ui-table-row-height-comfortable",
  "--mes-ui-table-header-height",
  "--mes-ui-table-cell-padding-x",
  "--mes-ui-table-cell-padding-y",
  "--mes-ui-table-tree-indent",
  "--mes-ui-table-action-size",
  "--mes-ui-data-table-min-width-wide",
  "--mes-ui-auth-card-title-line-clamp",
  "--mes-ui-table-head-bg",
  "--mes-ui-table-head-text",
  "--mes-ui-table-row-bg",
  "--mes-ui-table-row-hover-bg",
  "--mes-ui-table-row-selected-bg",
  "--mes-ui-table-row-group-bg",
  "--mes-ui-table-row-muted-bg",
  "--mes-ui-table-row-warning-bg",
  "--mes-ui-table-row-problem-bg",
  "--mes-ui-table-row-border",
  "--mes-ui-table-tree-line",
  "--mes-ui-table-tree-dot",
  "--mes-ui-table-tree-dot-active",
  "--mes-table-row-height",
  "--mes-table-header-height",
  "--mes-table-cell-padding-x",
  "--mes-table-cell-padding-y",
  "--mes-table-border-color",
  "--mes-table-header-bg",
  "--mes-table-header-text",
  "--mes-table-row-bg",
  "--mes-table-row-hover-bg",
  "--mes-table-row-selected-bg",
  "--mes-table-tree-indent",
  "--mes-table-action-size",
  "--mes-table-font-size",
  "--mes-table-line-height",
  "--mes-ui-radius-xs",
  "--mes-ui-radius-sm",
  "--mes-ui-radius-md",
  "--mes-ui-radius-lg",
  "--mes-ui-radius-xl",
  "--mes-ui-pill",
  "--mes-radius-none",
  "--mes-radius-xs",
  "--mes-radius-sm",
  "--mes-radius-md",
  "--mes-radius-lg",
  "--mes-radius-xl",
  "--mes-radius-pill",
  "--mes-ui-type-caption",
  "--mes-ui-type-body",
  "--mes-ui-type-section-title",
  "--mes-ui-type-table",
  "--mes-ui-type-small",
  "--mes-font-size-caption",
  "--mes-font-size-body",
  "--mes-font-size-table",
  "--mes-font-size-section",
  "--mes-font-size-section-title",
  "--mes-font-size-title",
  "--mes-ui-line-caption",
  "--mes-ui-line-body",
  "--mes-ui-line-section-title",
  "--mes-line-height-caption",
  "--mes-line-height-body",
  "--mes-line-height-table",
  "--mes-line-height-section-title",
  "--mes-ui-weight-regular",
  "--mes-ui-weight-medium",
  "--mes-ui-weight-semibold",
  "--mes-ui-weight-bold",
  "--mes-font-weight-regular",
  "--mes-font-weight-medium",
  "--mes-font-weight-semibold",
  "--mes-font-weight-bold",
  "--mes-ui-status-neutral-bg",
  "--mes-ui-status-neutral-border",
  "--mes-ui-status-neutral-text",
  "--mes-ui-status-success-bg",
  "--mes-ui-status-success-border",
  "--mes-ui-status-success-text",
  "--mes-ui-status-warning-bg",
  "--mes-ui-status-warning-border",
  "--mes-ui-status-warning-text",
  "--mes-ui-status-danger-bg",
  "--mes-ui-status-danger-border",
  "--mes-ui-status-danger-text",
  "--mes-ui-status-info-bg",
  "--mes-ui-status-info-border",
  "--mes-ui-status-info-text",
  "--mes-ui-status-demo-bg",
  "--mes-ui-status-demo-border",
  "--mes-ui-status-demo-text",
  "--mes-status-neutral-bg",
  "--mes-status-neutral-border",
  "--mes-status-neutral-text",
  "--mes-status-neutral-accent",
  "--mes-status-ready-bg",
  "--mes-status-ready-border",
  "--mes-status-ready-text",
  "--mes-status-ready-accent",
  "--mes-status-active-bg",
  "--mes-status-active-border",
  "--mes-status-active-text",
  "--mes-status-active-accent",
  "--mes-status-warning-bg",
  "--mes-status-warning-border",
  "--mes-status-warning-text",
  "--mes-status-warning-accent",
  "--mes-status-blocked-bg",
  "--mes-status-blocked-border",
  "--mes-status-blocked-text",
  "--mes-status-blocked-accent",
  "--mes-status-problem-bg",
  "--mes-status-problem-border",
  "--mes-status-problem-text",
  "--mes-status-problem-accent",
  "--mes-status-manual-bg",
  "--mes-status-manual-border",
  "--mes-status-manual-text",
  "--mes-status-manual-accent",
  "--mes-status-calculated-bg",
  "--mes-status-calculated-border",
  "--mes-status-calculated-text",
  "--mes-status-calculated-accent",
  "--mes-status-demo-bg",
  "--mes-status-demo-border",
  "--mes-status-demo-text",
  "--mes-status-demo-accent",
  "--mes-ui-gantt-plan-bg",
  "--mes-ui-gantt-distributed-bg",
  "--mes-ui-gantt-fact-bg",
  "--mes-ui-gantt-deficit-bg",
  "--mes-ui-gantt-transfer-bg",
  "--mes-ui-gantt-border",
  "--mes-ui-gantt-label",
  "--mes-ui-gantt-row-height",
  "--mes-ui-gantt-timeline-height",
  "--mes-ui-gantt-left-width",
  "--mes-ui-gantt-slot-radius",
  "--mes-ui-gantt-slot-border",
  "--mes-ui-gantt-slot-planned-bg",
  "--mes-ui-gantt-slot-distributed-bg",
  "--mes-ui-gantt-slot-active-bg",
  "--mes-ui-gantt-slot-completed-bg",
  "--mes-ui-gantt-slot-warning-bg",
  "--mes-ui-gantt-slot-problem-bg",
  "--mes-ui-gantt-slot-paused-bg",
  "--mes-ui-gantt-slot-transfer-bg",
  "--mes-ui-gantt-non-working-bg",
  "--mes-ui-gantt-dependency-color",
  "--mes-ui-gantt-dependency-active-color",
  "--mes-ui-gantt-dependency-warning-color",
  "--mes-ui-gantt-grid-line",
  "--mes-ui-gantt-timeline-bg",
  "--mes-ui-gantt-row-hover-bg",
  "--mes-ui-gantt-row-selected-bg",
  "--mes-gantt-row-height",
  "--mes-gantt-timeline-height",
  "--mes-gantt-left-width",
  "--mes-gantt-slot-radius",
  "--mes-gantt-slot-border",
  "--mes-gantt-slot-planned-bg",
  "--mes-gantt-slot-active-bg",
  "--mes-gantt-slot-warning-bg",
  "--mes-gantt-slot-problem-bg",
  "--mes-gantt-non-working-bg",
  "--mes-gantt-dependency-color",
  "--mes-ui-shadow-sm",
  "--mes-ui-shadow-md",
  "--mes-ui-shadow-overlay",
  "--mes-ui-shadow-lift",
  "--mes-ui-overlay-max-height",
  "--mes-ui-overlay-max-width",
  "--mes-ui-modal-width",
  "--mes-ui-drawer-width",
  "--mes-ui-z-dropdown",
];

export const UI_RUNTIME_DOM_NORMALIZER_CONTRACTS = [
  { component: "FormField", selector: "label:has(input), label:has(select), label:has(textarea), .form-field, .ui-form-field" },
  { component: "ActionButton", selector: "button, :is(label).primary-button, :is(label).secondary-button, .ui-action-button" },
  { component: "TableWrap", selector: "[data-layout='table'], .ui-table-wrap" },
  { component: "ModulePage", selector: ".module-data-page, .ui-module-page" },
  { component: "ModuleSidebar", selector: ".module-data-sidebar, .ui-module-sidebar" },
  { component: "ModuleWorkspace", selector: ".module-data-workspace, .ui-module-workspace" },
  { component: "ModuleContent", selector: ".module-data-content, .ui-module-content" },
  { component: "Panel", selector: ".module-panel, .ui-panel" },
  { component: "PanelHead", selector: ".modal-header, .drawer-header, .ui-panel-head" },
  { component: "PanelFooter", selector: ".modal-footer, .drawer-actions, .ui-panel-footer" },
  { component: "Toolbar", selector: ".ui-toolbar" },
  { component: "FilterBar", selector: ".ui-filter-bar" },
  { component: "EmptyState", selector: ".module-preview-empty, .ui-empty-state" },
  { component: "StatusToken", selector: ".mes-signal, .ui-status-token" },
  { component: "DemoBadge", selector: ".ui-demo-badge" },
  { component: "Modal", selector: ".modal, .ui-modal" },
  { component: "Drawer", selector: ".slot-drawer, .detail-drawer, .ui-drawer" },
  { component: "Dropdown", selector: ".dense-inline-select, .directory-column-filter, .mobile-module-switcher, .ui-dropdown" },
  { component: "GanttBar", selector: ".operation-slot, .ui-gantt-bar" },
];

export const UI_RUNTIME_TABLE_SCROLL_SELECTORS = [
  "[data-layout='table'], .ui-table-wrap",
];

export const UI_RUNTIME_QA_CLASS_CONTRACTS = [
  { requiredClass: "form-field", companionClass: "ui-form-field", label: "form-field должен идти вместе с ui-form-field" },
  { requiredClass: "directory-table-wrap", companionClass: "ui-table-wrap", label: "directory-table-wrap должен идти вместе с ui-table-wrap" },
  { requiredClass: "speki-structure-table-wrap", companionClass: "ui-table-wrap", label: "speki-structure-table-wrap должен идти вместе с ui-table-wrap" },
  { requiredClass: "primary-button", companionClass: "ui-action-button", label: "primary-button должен идти вместе с ui-action-button" },
  { requiredClass: "secondary-button", companionClass: "ui-action-button", label: "secondary-button должен идти вместе с ui-action-button" },
  { requiredClass: "icon-button", companionClass: "ui-action-button", label: "icon-button должен идти вместе с ui-action-button" },
  { requiredClass: "table-icon-button", companionClass: "ui-action-button", label: "table-icon-button должен идти вместе с ui-action-button" },
];

export const UI_RUNTIME_CONTROLLED_CLASS_PREFIXES = [
  "auth-prototype-",
  "auth-session-",
  "shift-master-board-",
  "shift-work-orders-",
  "timesheet-",
  "roles-",
  "production-structure-",
  "planning-table-",
  "matrix-",
  "planning-order-",
  "route-",
  "routes-",
  "speki-",
  "bom-",
  "nomenclature-",
  "employee-",
  "employees-",
  "directory-",
  "dispatch-",
  "supply-",
  "shop-",
  "shop-map-",
  "product-",
  "products-",
  "spec-",
  "specification-",
  "operation-",
  "slot-",
  "planning-",
  "module-",
  "auth-",
  "access-",
  "visual-",
  "row-",
  "bar-",
  "modal-",
  "app-",
];

export const UI_RUNTIME_DYNAMIC_CSS_ONLY_PREFIXES = [
  "is-",
  "status-",
  "dense-select-",
];

export const UI_RUNTIME_DYNAMIC_CSS_ONLY_CLASSES = [
  "production-row",
  "resource-row",
  "ui-table-actions",
  "ui-table-cell",
  "ui-table-empty",
  "ui-table-header",
  "ui-table-row",
  "ui-tree-cell",
  "ui-tree-toggle",
  "workCenter-row",
];

export const UI_RUNTIME_COMPATIBILITY_CSS_ONLY_CLASSES = [];

export function getUiRuntimeCoverageStatus(moduleId = "") {
  const id = String(moduleId || "").trim();
  if (HARD_UI_RUNTIME_MODULE_IDS.includes(id)) return "hard";
  if (SPECIAL_UI_RUNTIME_MODULE_IDS.includes(id)) return "special";
  if (PARTIAL_UI_RUNTIME_MODULE_IDS.includes(id)) return "partial";
  if (LEGACY_UI_RUNTIME_MODULE_IDS.includes(id)) return "legacy";
  return "unknown";
}

export function getUiRuntimeComponentContract(componentName = "") {
  const name = String(componentName || "").trim();
  return UI_RUNTIME_COMPONENT_CONTRACTS.find((contract) => contract.component === name) || null;
}
